[[pages]]
path = "00__Login.py"
name = "Login"
icon = "ğŸ”"

[[pages]]
path = "pages/01__Projects.py"
name = "Projects"
icon = "ğŸ“šâ€‹"

[[pages]]
path = "pages/02__Upload_Client_Documents.py"
name = "Upload Documents"
icon = "â¬†ï¸â€‹"

[[pages]]
path = "pages/03__Edit_Client_Documents.py"
name = "Edit Documents"
icon = "ğŸ› ï¸â€‹"

[[pages]]
path = "pages/04__Questionnaires.py"
name = "Questionnaires"
icon = "â”â€‹"

[[pages]]
path = "pages/05__Reports.py"
name = "Create Reports"
icon = "ğŸ“’"

[[pages]]
path = "pages/06__View_Reports.py"
name = "View Reports"
icon = "â€‹ğŸ“–â€‹"

[[pages]]
path = "pages/07__View_PDF.py"
name = "View_PDF"
icon = "ğŸ”â€‹"

[[pages]]
path = "pages/08__Categories.py"
name = "Categories"
icon = "ğŸ·ï¸"
